package enity;
// Generated May 13, 2018 4:18:36 PM by Hibernate Tools 4.3.1



/**
 * Stat generated by hbm2java
 */
public class Stat  implements java.io.Serializable {


     private String name;
     private int qte;

    public Stat() {
    }

    public Stat(String name, int qte) {
       this.name = name;
       this.qte = qte;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getQte() {
        return this.qte;
    }
    
    public void setQte(int qte) {
        this.qte = qte;
    }




}


