package enity;
// Generated May 13, 2018 4:18:36 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String id;
     private String password;
     private char type;

    public User() {
    }

    public User(String id, String password, char type) {
       this.id = id;
       this.password = password;
       this.type = type;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public char getType() {
        return this.type;
    }
    
    public void setType(char type) {
        this.type = type;
    }




}


